# Generated by Django 4.1 on 2022-09-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_customer_product_available_product_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('rajkot', 'Rajkot'), ('veraval', 'Veraval'), ('amreli', 'Amreli'), ('junagadh', 'Junagadh'), ('porbandar', 'Porbandar'), ('botad', 'Botad'), ('una', 'Una'), ('morbi', 'Morbi')], default='Rajkot', max_length=15),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On the way', 'On the way'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('Packed', 'Packed')], default='Pending', max_length=70),
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.CharField(choices=[('optimum', 'Optimum'), ('zplus', 'Zplus'), ('raymond', 'Raymond'), ('damodar', 'Damodar'), ('divinetouch', 'Divine-Touch'), ('saras', 'Saras'), ('donear', 'Donear'), ('navkar', 'Navkar'), ('srikot', 'Srikot')], default='saras', max_length=70),
        ),
    ]
