# Generated by Django 4.1 on 2022-09-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customer_district_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(choices=[('morbi', 'Morbi'), ('rajkot', 'Rajkot'), ('junagadh', 'Junagadh'), ('botad', 'Botad'), ('amreli', 'Amreli'), ('porbandar', 'Porbandar'), ('una', 'Una'), ('veraval', 'Veraval')], default='Rajkot', max_length=15),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Packed', 'Packed'), ('On the way', 'On the way'), ('Cancel', 'Cancel')], default='Pending', max_length=70),
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.CharField(choices=[('damodar', 'Damodar'), ('raymond', 'Raymond'), ('saras', 'Saras'), ('navkar', 'Navkar'), ('zplus', 'Zplus'), ('optimum', 'Optimum'), ('srikot', 'Srikot'), ('donear', 'Donear'), ('divinetouch', 'Divine-Touch')], default='saras', max_length=70),
        ),
    ]
