# Generated by Django 4.1 on 2022-08-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_customer_rename_prod_id_cart_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('On the way', 'On the way')], default='Pending', max_length=70),
        ),
        migrations.AlterField(
            model_name='product',
            name='fabric_type',
            field=models.CharField(choices=[('alpha', 'ALPHA'), ('magic', 'MAGIC'), ('bsy', 'BSY'), ('cotton', 'COTTON'), ('lycra', 'LYCRA'), ('metti', 'METTI'), ('twill', 'TWILL')], default='magic', max_length=15),
        ),
    ]
