# Generated by Django 4.1 on 2022-08-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_orderplaced_status_alter_product_fabric_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fabric_type',
            field=models.CharField(choices=[('alpha', 'ALPHA'), ('magic', 'MAGIC'), ('bsy', 'BSY'), ('cotton', 'COTTON')], default='magic', max_length=15),
        ),
    ]
