# Generated by Django 4.1 on 2022-08-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_product_fabric_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Packed', 'Packed'), ('Cancel', 'Cancel'), ('On the way', 'On the way'), ('Accepted', 'Accepted')], default='Pending', max_length=70),
        ),
    ]
