# Generated by Django 4.1 on 2022-08-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product_available_alter_orderplaced_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Packed', 'Packed'), ('On the way', 'On the way'), ('Accepted', 'Accepted')], default='Pending', max_length=70),
        ),
    ]
