# Generated by Django 4.1 on 2022-09-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_username_cart_user_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted')], default='Pending', max_length=70),
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.CharField(choices=[('srikot', 'Srikot'), ('raymond', 'Raymond'), ('optimum', 'Optimum'), ('navkar', 'Navkar'), ('damodar', 'Damodar'), ('zplus', 'Zplus'), ('divinetouch', 'Divine-Touch'), ('saras', 'Saras'), ('donear', 'Donear')], default='saras', max_length=70),
        ),
    ]
