# Generated by Django 4.1 on 2022-09-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_orderplaced_status_alter_product_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On the way', 'On the way')], default='Pending', max_length=70),
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.CharField(choices=[('optimum', 'Optimum'), ('srikot', 'Srikot'), ('raymond', 'Raymond'), ('donear', 'Donear'), ('saras', 'Saras'), ('zplus', 'Zplus'), ('navkar', 'Navkar'), ('divinetouch', 'Divine-Touch'), ('damodar', 'Damodar')], default='saras', max_length=70),
        ),
    ]
