# Generated by Django 4.1 on 2022-09-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_orderplaced_status_alter_product_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On the way', 'On the way'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=70),
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.CharField(choices=[('donear', 'Donear'), ('navkar', 'Navkar'), ('damodar', 'Damodar'), ('srikot', 'Srikot'), ('zplus', 'Zplus'), ('raymond', 'Raymond'), ('optimum', 'Optimum'), ('divinetouch', 'Divine-Touch'), ('saras', 'Saras')], default='saras', max_length=70),
        ),
    ]
